Hw09 struct validator
S-Dionis/otus_go_hw pull request #8
Opened 2024-07-14 20:22 UTC by S-Dionis

## Домашнее задание №9 «Валидатор структур»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)

### Критерии оценки
- [ ] Пайплайн зелёный - 3 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2024-07-15 03:30 UTC, dshemin requested changes

2024-07-15 03:30 UTC, dshemin commented on hw09_struct_validator/validator.go
> +	var resultString string
Важно:

Для сборки строк лучше использовать strings.Builder

2024-07-15 03:30 UTC, dshemin commented on hw09_struct_validator/validator.go
> +		tag := field.Tag.Get("validate")
Критично:

Обратите внимание на задание:
```
Она должна валидировать публичные поля входной структуры на основе структурного тэга validate
```

Нужно валидировать только публичные поля. У Вас такой проверки нет.

2024-07-15 03:30 UTC, dshemin commented on hw09_struct_validator/validator_test.go
>  			_ = tt
Важно:

Эту строчку можно ужалить.

2024-07-15 03:30 UTC, dshemin commented on hw09_struct_validator/validator_test.go
> +			require.Equal(t, tt.expectedErr, err)
Важно:

Для сравнения ошибок лучше использовать require.ErrorIs

2024-07-15 19:26 UTC, S-Dionis commented on hw09_struct_validator/validator_test.go
> +			require.Equal(t, tt.expectedErr, err)
у меня errors.Is здесь не работает, на 2 одинаковые ошибки выдает false

2024-07-16 02:03 UTC, dshemin requested changes

2024-07-16 02:03 UTC, dshemin commented on hw09_struct_validator/validator.go
> +		if tag == "" || !(field.PkgPath == "") {
Критично:

https://pkg.go.dev/reflect#StructField.IsExported

2024-07-16 02:03 UTC, dshemin commented on hw09_struct_validator/validator_test.go
> +			require.Equal(t, tt.expectedErr, err)
Увидел что тут не только константные ошибки проверяются.

2024-07-17 04:43 UTC, dshemin approved these changes

2024-07-24 20:23 UTC, merged